configuration:
  
#  - --version 5.24.1.1
#  - --version 5.24.1.1 --x86
  - --version 5.20.3.3
  - --version 5.20.3.3 --x86
  - --version 5.14.4.1
  - --version 5.14.4.1 --x86
  
install:
  - choco install --allowemptychecksum strawberryperl %configuration%
  - path C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - perl -V
  - cd Measurement
  - cpanm --installdeps -v .

build_script:
  - perl ./Build.PL
  - ./Build
  - prove --verbose --blib --recurse t
  