environment:
  matrix:
    - sp_config: --version 5.20.3.3
    - sp_config: --version 5.20.3.3 --x86
      
install:
  - choco install --allowemptychecksum strawberryperl %sp_config%
  - path C:\strawberry\perl\bin;C:\strawberry\perl\site\bin;C:\strawberry\c\bin;%PATH%
  - perl -V
  
  - choco install gnuplot.portable
  - path C:\Program Files\gnuplot\bin;%PATH%
  - gnuplot --version
  
  - cd Measurement
  - cpanm --installdeps -v .
  - cpanm -v PDL::Graphics::Gnuplot
  
build_script:
  - perl ./Build.PL
  - ./Build
  - prove --verbose --blib --recurse t
  